[package]
name = "just-serve"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
pico-args = "0.5.0"
tokio = { version = "1.45.1", features = ["full"] }
tower-http = { version = "0.6.6", features = ["cors", "fs"] }
